{% set name = "crocoddyl" %}
{% set version = "2.99.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../../crocoddyl
  patches:
    - patches/0001-Bump-to-agm-ws-2023-special-2.99.2-version.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pinocchio-devel =2.99.0                # [build_platform != target_platform]
  host:
    - eigen
    - eigenpy
    - pinocchio-devel =2.99.0
    - boost
    - python
    - example-robot-data =4.99.8
    - numpy
  run:
    - eigen
    - eigenpy
    - boost
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
  imports:
    - crocoddyl

about:
  home: http://github.com/loco-3d/crocoddyl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Crocoddyl is an optimal control library for robot control under contact sequence. Its solver is based on various efficient Differential Dynamic Programming (DDP)-like algorithms.
  dev_url: https://github.com/loco-3d/crocoddyl

extra:
  recipe-maintainers:
    - jcarpent
