name: Build and publish conda packages for Mac M1

on: [push, pull_request]

jobs:
  build-publish-conda:
    name: "Build and publish conda packages"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["self-hosted-arm64"]
        build_type: [Release]
        python-version: ["3.10"]


    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install conda environment
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        conda install anaconda-client conda-build -c conda-forge

    - name: Show conda config
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    - name: Clone repositories
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        git clone https://github.com/humanoid-path-planner/hpp-fcl.git -b hppfcl3x --recursive
        git clone https://${{ secrets.GITLAB_TOKEN_NAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.inria.fr/jucarpen/pinocchio -b pinocchio-3x --recursive
        git clone https://github.com/Gepetto/example-robot-data.git -b v4.0.8 --recursive
        git clone https://github.com/jorisv/crocoddyl.git -b topic/fix-stub-gen --recursive
        git clone https://${{ secrets.GH_TOKEN_NAME }}:${{ secrets.GH_TOKEN }}@github.com/Simple-Robotics/proxnlp.git -b agimus-ws-2023 --recursive
        git clone https://${{ secrets.GH_TOKEN_NAME }}:${{ secrets.GH_TOKEN }}@github.com/Simple-Robotics/proxddp.git -b agimus-ws-2023 --recursive
        ls -al

    - name: Build hpp-fcl conda package
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        cd conda/recipes
        conda build hpp-fcl -c conda-forge

    - name: Build pinocchio conda package
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        cd conda/recipes
        conda build pinocchio -c conda-forge

    - name: Build example-robot-data conda package
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        cd conda/recipes
        conda build example-robot-data -c conda-forge

    - name: Build crocoddyl conda package
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        cd conda/recipes
        conda build crocoddyl -c conda-forge

    - name: Build proxnlp conda package
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        cd conda/recipes
        conda build proxnlp -c conda-forge

    - name: Build proxddp conda package
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        cd conda/recipes
        conda build proxddp -c conda-forge

    - name: Publish packages
      shell: bash -l {0}
      run: |
        conda activate agm-ws-2023-py${{ matrix.python-version }}
        export ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
        python scripts/upload_packages.py
