name: Build and publish conda packages

on: [push, pull_request]

jobs:
  build-publish-conda:
    name: "Build and publish conda packages"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # os: ["ubuntu-latest", "macos-latest"]
        os: ["ubuntu-latest"]
        build_type: [Release]
        python-version: ["3.12"]


    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ci
        auto-update-conda: true
        environment-file: .github/workflows/conda/environment.yml
        python-version: ${{ matrix.python-version }}

    - name: Clone repositories
      shell: bash -l {0}
      run: |
        conda activate ci
        git clone https://${{ secrets.GITLAB_TOKEN_NAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.inria.fr/jucarpen/pinocchio -b pinocchio-3x
        git clone https://github.com/humanoid-path-planner/hpp-fcl.git -b hppfcl3x
        git clone https://${{ secrets.GH_TOKEN_NAME }}:${{ secrets.GH_TOKEN }}@github.com/Simple-Robotics/proxnlp.git -b agimus-ws-2023
        git clone https://${{ secrets.GH_TOKEN_NAME }}:${{ secrets.GH_TOKEN }}@github.com/Simple-Robotics/proxddp.git -b agimus-ws-2023
        ls
